### ISSUE TITLE
Samsung GT-N7108 视频压缩失败

### ISSUE THREAD

**Issue by Nstd** [wuxiaoqiang625/VideoCompress#4]
Android版本：4.1

报错如下：
``` java
Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.iceteck.silicompressorr.videocompression.VideoController.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I
        at com.iceteck.silicompressorr.videocompression.VideoController.convertVideoFrame(Native Method)
        at com.iceteck.silicompressorr.videocompression.VideoController.convertVideo(VideoController.java:640)
        at com.iceteck.silicompressorr.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:53)
        at com.iceteck.silicompressorr.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:34)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
        at java.lang.Thread.run(Thread.java:856) 
```

**Comment by Nstd** [comment]
得用api 18及以上的Android版本才行
